version: '3.8'
services:
  db:
    build:
      context: ./db
      dockerfile: ./Dockerfile
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
      - PGDATA=/var/lib/postgresql/data/db-nest-api/
    volumes:
      - pg-data:/var/lib/postgresql/data
    command:
      ['postgres', '-c', 'logging_collector=on', '-c', 'log_statement=all']
    networks:
      - my_network
    ports:
      - ${PG_PORT}:${PG_PORT}
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: mcnic/rs-nest-service-app
    restart: unless-stopped
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - LOCALE=${LOCALE}
      - TIME_ZONE=${TIME_ZONE}
      - LOG_TO_CONSOLE=${LOG_TO_CONSOLE}
      - LOG_TO_FILE=${LOG_TO_FILE}
      - LOG_FILE_PATH=${LOG_FILE_PATH}
      - ERROR_FILE_PATH=${ERROR_FILE_PATH}
      - LOG_FILE_MAX_SIZE=${LOG_FILE_MAX_SIZE}
      - BCRYPT_SALT_ROUND=${BCRYPT_SALT_ROUND}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_TIME=${JWT_EXPIRE_TIME}
      - JWT_SECRET_REFRESH_KEY=${JWT_SECRET_REFRESH_KEY}
      - JWT_REFRESH_EXPIRE_TIME=${JWT_REFRESH_EXPIRE_TIME}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network
    volumes:
      - ./logs:/app/logs
      - ./src:/app/src

  pgadmin:
    image: dpage/pgadmin4
    restart: on-failure
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - PGADMIN_LISTEN_PORT=80
    ports:
      - '8080:80'
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      db:
        condition: service_healthy
    networks:
      - my_network

volumes:
  pg-data:
  pg-log:
  pgadmin:

networks:
  my_network:
    driver: bridge
